soccer_predictions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

from wc2022 import views
from wc2018 import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('wc2022/', include('wc2022.urls')),
    path('wc2018/', include('wc2018.urls')),
    path('euro2024/', include('euro2024.urls')),
    path('', lambda req: redirect('/wc2022/'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wc2018/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'wc2018'

urlpatterns = [
    path('', views.pronostics, name='pronostics'),
    path('pronostics/', views.pronostics, name='pronostics'),
    path('pronostiquer/', views.pronostiquer, name='pronostiquer'),
    path('teams/', views.teams, name='teams'),
    path('groups/', views.groups, name='groups'),
    path('resultats/', views.resultats, name='resultats'),
    path('knockout/', views.knockout, name='knockout'),
    path('classement/', views.classement, name='classement'),
    path('record/', views.record, name='record'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wc2018/models.py
from django.db import models
from datetime import datetime

class Winner(models.IntegerChoices):
        Team1 = 1
        Team2 = 2
        Draw = 3

# Create your models here.
# class User(models.Model):
#     name = models.CharField(max_length=20, null=False)
#     password = models.CharField(max_length=200)
#     def __str__(self):
#         return self.name

class Round(models.Model):
    round_name = models.CharField(max_length=200, null=False)
    extra_time_possible = models.BooleanField()
    def __str__(self):
        return self.round_name

class Team(models.Model):
    name = models.CharField(max_length=50, null=True)
    iso2 = models.CharField(max_length=6, null=True)
    def __str__(self):
        return self.name

class Group(models.Model):
    name = models.CharField(max_length=1, null=True)
    team1 = models.ForeignKey(Team, null=False, related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team, null=False, related_name='team2', on_delete=models.CASCADE)
    team3 = models.ForeignKey(Team, null=False, related_name='team3', on_delete=models.CASCADE)
    team4 = models.ForeignKey(Team, null=False, related_name='team4', on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Match(models.Model):
    match_id = models.IntegerField(null=False)
    match_round = models.ForeignKey(Round, on_delete=models.CASCADE)
    team1 = models.ForeignKey(Team, null=False, related_name='home', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team, null=False, related_name='away', on_delete=models.CASCADE)
    match_date = models.DateTimeField('Date du match')
    def __str__(self):
        return str(self.team1) + " - " + str(self.team2)

class Result(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE, null=False)
    score_team1 = models.IntegerField()
    score_team2 = models.IntegerField()
    extratime = models.BooleanField()
    score_extratime_team1 = models.IntegerField(null=True)
    score_extratime_team2 = models.IntegerField(null=True)
    vainqueur = models.IntegerField(choices=Winner.choices, null=True)
    def __str__(self):
        return str(self.match.team1) + " - " + str(self.match.team2) + " || " + str(self.score_team1) +" - " + str(self.score_team2)

class Prono(models.Model):
    pronostiqueur = models.ForeignKey("auth.User", on_delete=models.CASCADE, null=False, related_name="wc2018Prono")
    prono_date = models.DateTimeField(default=datetime.now, blank=True)
    # result = models.ForeignKey(Result, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE, null=False)
    score_team1 = models.IntegerField()
    score_team2 = models.IntegerField()
    extratime = models.BooleanField()
    score_extratime_team1 = models.IntegerField(null=True)
    score_extratime_team2 = models.IntegerField(null=True)
    vainqueur = models.IntegerField(choices=Winner.choices, null=True)
    def __str__(self):
        return str(self.pronostiqueur) + ": " + str(self.match.team1) + " - " + str(self.match.team2) + " || " + str(self.score_team1) +" - " + str(self.score_team2) + " @" +str(self.prono_date)
        # return str(self.pronostiqueur.name) + ": " + str(self.result)

wc2018/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Prono, Result, Team, Match, Round, Group, Winner
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime, timedelta
import functools
import re

########################################
@login_required
def teams(request):
    teams = Team.objects.order_by('name')
    t = []
    # Filter special teams for knockout stage
    for team in teams:
        if re.match("[LM][0-9]*", team.name) == None and re.match("[WR][A-H]", team.name) == None:
            t.append(team)
    return render(request, request.resolver_match.app_name + '/teams.html', {
        'teams': t
    })
########################################

def __compare_rankings(r1, r2):
    # 1. Points obtained in all group matches;
    if r1.pts < r2.pts:
        return 1
    if r1.pts > r2.pts:
        return -1
    
    # From now on we assume both team have the same number of points
    assert(r1.pts == r2.pts)

    # 2. Goal difference in all group matches;
    if r1.gd < r2.gd:
        return 1
    if r1.gd > r2.gd:
        return -1
    
    # From now on we assume both team have the same goal difference
    assert(r1.gd == r2.gd)
    
    # 3. Number of goals scored in all group matches;
    if r1.gf < r2.gf:
        return 1
    if r1.gf > r2.gf:
        return -1

    #     Points obtained in the matches played between the teams in question;
    #     Goal difference in the matches played between the teams in question;
    #     Number of goals scored in the matches played between the teams in question;
    #     Fair play points in all group matches (only one deduction can be applied to a player in a single match):
    #         Yellow card: -1 point;
    #         Indirect red card (second yellow card): -3 points;
    #         Direct red card: -4 points;
    #         Yellow card and direct red card: -5 points;
    #     Drawing of lots.
    
    return 0
    
def __compute_group_rankings(results, matches, teams, groups):
    class Ranking:
        def __init__(self, team, group):
            self.team = team
            self.group = group
            self.gf = 0
            self.ga = 0
            self.gd = 0
            self.w = 0
            self.l = 0
            self.d = 0
            self.pld = 0
            self.pts = 0
            self.pos = 0
            
        def __str__(self):
            return self.team.name + ":" + str(self.pts)
                
    r = []
    for group in groups.all():
        # print(group)
        ranking_group = {}
        for team in [group.team1, group.team2, group.team3, group.team4]:
            ranking_group[team.name] = Ranking(team, group)
        # print("ranking_group=", ranking_group)
        # for match in matches.all():
        for team in [group.team1, group.team2, group.team3, group.team4]:
            tmp = results.filter(match__team1_id=team.id)
            # print("  match=", match)
            #     print("    team=", team)
            for result in tmp:
                try:
                    # if match.team1.name != team.name:
                    #     continue
                    # result = results.get(match__team1_id=team.id)
                    # print("      result=", result)
                    ranking_group[result.match.team1.name].gf += result.score_extratime_team1
                    ranking_group[result.match.team1.name].ga += result.score_extratime_team2
                    ranking_group[result.match.team1.name].gd += result.score_extratime_team1 - result.score_extratime_team2

                    ranking_group[result.match.team2.name].gf += result.score_extratime_team2
                    ranking_group[result.match.team2.name].ga += result.score_extratime_team1
                    ranking_group[result.match.team2.name].gd += result.score_extratime_team2 - result.score_extratime_team1

                    ranking_group[result.match.team1.name].pld += 1
                    ranking_group[result.match.team2.name].pld += 1

                    if result.score_extratime_team1 > result.score_extratime_team2:
                        ranking_group[result.match.team1.name].w += 1
                        ranking_group[result.match.team1.name].pts += 3
                        ranking_group[result.match.team2.name].l += 1
                    elif result.score_extratime_team1 < result.score_extratime_team2:
                        ranking_group[result.match.team2.name].w += 1
                        ranking_group[result.match.team2.name].pts += 3
                        ranking_group[result.match.team1.name].l += 1
                    else: 
                        ranking_group[result.match.team2.name].d += 1
                        ranking_group[result.match.team2.name].pts += 1
                        ranking_group[result.match.team1.name].d += 1
                        ranking_group[result.match.team1.name].pts += 1
                           

                except Result.DoesNotExist as e:
                    continue
                
        for team in [group.team1, group.team2, group.team3, group.team4]:
            r.append(ranking_group[team.name])

    for group in groups.all():
        group_ranking = {}
        for team in [group.team1, group.team2, group.team3, group.team4]:
            for ranking in r:
                if ranking.team.name == team.name:
                    group_ranking[team.name] = ranking
        decorated = [(g.pts, i, g) for i, g in enumerate(group_ranking.values())]
        gr = sorted(group_ranking.values(), key=functools.cmp_to_key(__compare_rankings))
        # decorated.sort(reverse=True)
        # print(decorated)
        # gr = [gr for pts, i, gr in decorated]
        # print("gr=", gr)
        # for k, v in gr.items():
        for i in range(len(gr)):
            # print("group i=", v.team.name)
            team_name = gr[i].team.name
            # print("group i=", team_name)
            group_ranking[team_name].pos = i + 1

    return r

########################################
@login_required
def resultats(request):
    results = Result.objects
    matches = Match.objects
    teams = Team.objects
    groups = Group.objects

    rankings = __compute_group_rankings(results, matches, teams, groups)
    
    return render(request, request.resolver_match.app_name + '/resultats.html', {
        'teams': teams.order_by('name'),
        'groups': groups.order_by('name'),
        'results': results,
        'groups': Group.objects,
        'rankings': rankings,
    })

########################################
@login_required
def groups(request):
    return render(request, request.resolver_match.app_name + '/groups.html', {
        'teams': Team.objects.order_by('name'),
        'groups': Group.objects.order_by('name')
    })

def __compute_points_for_user_on_result(prono, result):
    points = 0
    # print("match", prono.match, ", prono=", prono, ", result ", result)
    if result.score_team1 > result.score_team2 or (result.extratime == True and result.score_extratime_team1 > result.score_extratime_team2):
        match_winner = 1
    elif result.score_team1 < result.score_team2 or (result.extratime == True and result.score_extratime_team1 < result.score_extratime_team2):
        match_winner = 2
    else:
        match_winner = 3

    # print(match_winner, prono.vainqueur)
    if match_winner == prono.vainqueur:
        # Has identifier the right winner and the right score: 15 points
        if (result.score_team1 == prono.score_team1 and result.score_team2 == prono.score_team2) or (result.extratime == prono.extratime and (result.score_extratime_team1 == prono.score_extratime_team1 and result.score_extratime_team2 == prono.score_extratime_team2)):
            # print("15 points for right score for match", prono.match)
            return 15
        # right winner : 5 points
        # print("5 points for winner for match", prono.match)
        points = 5
    else:
        points = 0
        return points
    
    goal_diff_real = abs(result.score_team1 - result.score_team2)
    if result.extratime == True:
        goal_diff_real = abs(result.score_extratime_team1 - result.score_extratime_team2)
    goal_diff_prono = abs(prono.score_team1 - prono.score_team2)
    if prono.extratime == True:
        goal_diff_prono = abs(prono.score_extratime_team1 - prono.score_extratime_team2)

    if goal_diff_prono == goal_diff_real:
        points_for_goal_diff = 4 - abs(result.score_team1 - prono.score_team1)
        if points_for_goal_diff > 0:
            points += points_for_goal_diff
            # print(points_for_goal_diff, "points for goal diff for ", prono.match)

    points_for_goal_team1 = 2 - abs(result.score_team1 - prono.score_team1)
    if points_for_goal_team1 > 0:
        points += points_for_goal_team1
        # print(points_for_goal_team1, "points for goal team1 for ", prono.match)
        
    points_for_goal_team2 = 2 - abs(result.score_team2 - prono.score_team2)
    if points_for_goal_team2 > 0:
        points += points_for_goal_team2
        # print(points_for_goal_team2, "points for goal team2 for ", prono.match)
    
    return points

########################################
@login_required
def classement(request):
    results = Result.objects
    users = User.objects
    pronos = Prono.objects
    result_pronos = []
    user_points = []
    points_dict = {}
    class UserTotalPoints:
        def __init__(self, user):
            self.user = user
            self.total_points = 0
        def __str__(self):
            return self.user + " " + str(self.total_points)
        
    for u in users.all():
        tmp = UserTotalPoints(u.get_username())
        user_points.append(tmp)
        points_dict[u.get_username()] = tmp
    class ResultatProno:

wc2018/templates/wc2018/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}{% endblock %}
    </title>
    {% block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    {% block styles %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock %}
    
    {% block js %}   
    <script src="https://code.jquery.com/jquery-3.6.1.slim.min.js" integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
	    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
	    crossorigin="anonymous"></script>    
   {% endblock %}
</head>

<body>
  
{% block nav_header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <img src="{% static 'wc2018/2018_FIFA_World_Cup.svg' %}" alt="" width="120" height="96">
    <span class="navbar-text">Coupe du Monde 2018</span>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      {% endblock %}
      {% block nav %}
      <li id="li_pronostics" class="nav-item">
        <a id="pronostics" class="nav-link" href="{% url 'wc2018:pronostics' %}">Pronostics</a>
      </li>
      <li id="li_pronostiquer" class="nav-item">
        <a id="pronostiquer" class="nav-link" href="{% url 'wc2018:pronostiquer' %}">Pronostiquer</a>
      </li>
      <li id="li_teams" class="nav-item">
        <a id="teams" class="nav-link" href="{% url 'wc2018:teams' %}">Equipes</a>
      </li>
      <li id="li_groups" class="nav-item">
        <a id="groups" class="nav-link" href="{% url 'wc2018:groups' %}">Poules</a>
      </li>
      <li id="li_resultats" class="nav-item">
        <a id="resultats" class="nav-link" href="{% url 'wc2018:resultats' %}">Résultats</a>
      </li>
      <li id="li_knockout" class="nav-item">
	<a id="knockout" class="nav-link" href="{% url 'wc2018:knockout' %}">Tableau final</a> 
      </li>
      <li id="li_ranking" class="nav-item">
        <a id="ranking" class="nav-link" href="{% url 'wc2018:classement' %}">Classement</a>
      </li>
      {% endblock %}
{% block nav_footer %}
    </ul>
  </div>
</nav>
            {% endblock %}

    <main role="main" class="container top-pushed">
        <div class="jumbotron">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>

</html>

wc2018/templates/wc2018/classement.html
{% extends "wc2018/base.html" %}

{% load static %}

{% block title %}
    Coupe du Monde 2018
{% endblock %}

{% block styles %}
    {{ block.super }}
{% endblock %}

{% block content %}
 {% for round in rounds.all %}
 <h2>{{ round.round_name }}</h2>
<div class="col-md-4 row" style="width:25%; display:table">
<table class="table table-striped table-hover" style="white-space: nowrap">
<thead class="thead-dark">
<tr>
    <th class="w-auto" scope="col">Match</th>
    <th class="w-auto" scope="col">Score</th>
    {% for user in users.all %}
      <th class="w-auto" scope="col">{{ user }}</th>
    {% endfor user %}
</tr>
</thead>
<tbody>
  {% for result in results.all %}
   {% if result.match.match_round.round_name|lower == round.round_name|lower %}

<tr>
  <td class="w-auto">
    <div>
      <img src="https://flagcdn.com/w20/{{ result.match.team1.iso2 }}.png" srcset="https://flagcdn.com/w40/{{ result.match.team1.iso2 }}.png 2x" width="20"> &nbsp; {{ result.match.team1.name }}&nbsp;-&nbsp;{{ result.match.team2.name }}&nbsp;  <img src="https://flagcdn.com/w20/{{ result.match.team2.iso2 }}.png" srcset="https://flagcdn.com/w40/{{ result.match.team2.iso2 }}.png 2x" width="20">
</div>
  </td>
  <td class="w-auto">
    {{ result.score_team1 }} - {{ result.score_team2 }} 
  </td>
  {% for user in users.all %}
  {% for result_prono in result_pronos %}
    {% if result_prono.match_id == result.match.match_id %}
      <td class="w-auto">
      {% if result_prono.user|lower == user|lower %}
          {{ result_prono.points }} 
        {% else %}
          0
        {% endif %}
      </td>
    {% endif %}
  {% endfor prono %}
  {% endfor user %}
</tr>
{% endif %}
{% endfor result %}
<tbody>
  <tfoot>
    <tr>
      <td class="w-auto" colspan=2>
	TOTAL
      </td>
      {% for p in users_totalpoints %}
      {% for user in users.all %}
      {% if p.user|lower == user|lower %}
        <td class="w-auto">
  	  {{ p.total_points }}
        </td>
	{% endif %}
      {% endfor user %}
      {% endfor p %}
    </tr>
  </tfoot>
</table>
</div>
      {% endfor round %}
<script>
document.getElementById("ranking").innerHTML += "<span class=\"sr-only\">(current)</span>";
  document.getElementById("li_ranking").classList.add("active");
</script>

{% endblock %}

wc2018/templates/wc2018/pronostiquer.html
{% extends "wc2018/base.html" %}

{% load static %}
{% load wc2018_extratags %}

{% block title %}
    Coupe du Monde 2018
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap4.min.js"></script>
    
<script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.print.min.js"></script>

{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">
{% endblock %}


    {% block content %}
<h1> Pronostics de {{ user }} </h1>
 {% for round in ordered_rounds %}
 {% if round.id <= current_prediction_round %}
  <form action="{% url 'wc2018:record' %}" method="post">
    <div class="form-row align-items-center">
  {% csrf_token %}
<fieldset>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="table-responsive">
      <table id="table{{ round.id }}" class="table table-striped table-hover"
	     style="white-space: nowrap">
      <thead class="thead-dark">
  <tr>
      <th style="text-align:center;background-color: #666666" colspan="8" scope="col"> {{ round.round_name }}</th>
  </tr>
  <tr>
    <th class="w-auto" scope="col">#</th>
    <th class="w-auto" scope="col">Date</th>
    <th class="w-auto" scope="col">Equipe 1</th>
    <th class="w-auto" scope="col">score1</th>
    <th class="w-auto" scope="col"> </th>
    <th class="w-auto" scope="col">score2</th>
    <th class="w-auto" scope="col">Equipe 2</th>
    <th class="w-auto" scope="col">Temps restant</th>
  </tr>
      </thead>
       <tbody>
 {% for m in matches %}
{% if m.match.match_round.id == round.id %} 
<!-- { % if m.match_round.round_name|lower == round.round_name|lower %}  -->
 <tr>
    <td class="w-auto">{{m.match.match_id }}</td>
    <td data-order="{{m.match_date|date:"Y-m-d-H-i" }}" class="w-auto">{{m.match_date|date:"d F Y H:i" }}</td>
    <!-- <td class="w-auto">{{m.match_date|date:"d F Y H:i" }}</td> -->
    
    <td class="w-auto">
      <img src="https://flagcdn.com/w20/{{ m.match.team1.iso2 }}.png" srcset="https://flagcdn.com/w40/{{ m.match.team1.iso2 }}.png 2x" width="20">
      {{ m.match.team1.name }}
    </td>
      {% for p in pronostics %}
        {% if p.match.match_id == m.match.match_id %}
          <input type="hidden" name="matchid" value="{{ m.match_id }}"/> </td>
<td class="w-auto">
  <div >
{% if todays_date|date:"Y-m-d H:i" < p.match.match_date|date:"Y-m-d H:i" %}
  <input type="number" class="form-control mb-2" style="min-width: 75px;" name="score1" id="score1_{{m.match.match_id}}" min="0" max="12" value="{{ p.score_team1 }}"/>
{% else %}
  <input type="hidden"name="score1" id="score1_{{m.match.match_id}}" value="{{ p.score_team1 }}"/>
  {{ p.score_team1 }}
{% endif %}
  </div>
</td>

<td class="w-auto">-</td>

<td class="w-auto">
<div >
  {% if todays_date|date:"Y-m-d H:i" < p.match.match_date|date:"Y-m-d H:i" %}
  <input type="number" class="form-control mb-2" style="min-width: 75px;" name="score2" id="score2_{{m.match_id}}" min="0" max="12" value="{{ p.score_team2 }}"/> 
  {% else %}
  <input type="hidden"name="score2" id="score2_{{m.match_id}}" value="{{ p.score_team2 }}"/>
  {{ p.score_team2 }}
{% endif %}
</div>
</td>
{% endif %}
{% endfor %}
<td class="w-auto">
  {{ m.match.team2.name }}
      <img src="https://flagcdn.com/w20/{{ m.match.team2.iso2 }}.png" srcset="https://flagcdn.com/w40/{{ m.match.team2.iso2 }}.png 2x" width="20">
</td>

<td class="w-auto">
  {% if m.match.match_date|votetime_days != 0 %}
      {{m.match.match_date|votetime_days }}
  {% endif %}
</td>

</tr>
{% endif %}
{% endfor %}
 </tbody>
</fieldset>
{% endif %}
{% endfor %}

</table>
</div>
<input type="submit" value="Enregistrer">
</div>
</form>

<script>
     
$(document).ready(function () {
    $('#table1').DataTable({
        paging: false,
	info: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
	buttons: [
        ],
	
    },
  );
    $('#table2').DataTable({
        paging: false,
	info: false,
	searching: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
        buttons: [
        ]
    } );
    $('#table3').DataTable({
        paging: false,
	info: false,
	searching: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
        buttons: [
        ]
    } );
    $('#table4').DataTable({
        paging: false,
	info: false,
	searching: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
        buttons: [
        ]
    } );
    $('#table5').DataTable({
        paging: false,
	info: false,
	searching: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
        buttons: [
        ]
    } );
    $('#table6').DataTable({
        paging: false,
	info: false,
	searching: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
        buttons: [
        ]
    } );
    $('#table7').DataTable({
        paging: false,
	info: false,
	searching: false,
	columns: [
	    { orderable: true },
	    { orderable: true },
	    { orderable: true },
	    { orderable: false },
	    { orderable: false},
	    { orderable: false },
	    { orderable: true },
	    { orderable: false },
	],
	dom: 'Bfrtip',
        buttons: [
            
        ]
    } );
});
</script>
<script>
  document.getElementById("pronostiquer").innerHTML += "<span class='sr-only'>(current)</span>";
  document.getElementById("li_pronostiquer").classList.add("active");
</script>
{% endblock %}